name: Code quality # workflow name
description: Workflow for code quality analysis

# === code quality execution ===
runs:
  using: composite
  
  steps: # tasks
    - name: Set Github Workspace # access Github Workspace
      uses: actions/checkout@v2
    - name: Set up Python 3.x # set architecture and Python3
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
        architecture: "x64" # architecture
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install flake8

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

