version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

submodules:
  exclude: all

python:
  version: "3.7"
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .
      extra_requirements:
        - docs