name: Run unit tests # workflow name

on:
  workflow_call

# parallel jobs to perform
jobs:
  # === unittest execution ===
  run_unittests:
    runs-on: ubuntu-latest # runner

      - name: Run unittests # run unittests
        run: python tests/test.py

      - name: Print log # print log
        if: always()
        run: |
          if [ -f test.log ]; then cat test.log; fi
