name: Build wheels
description: Builds wheels for release

runs:
  using: composite

  steps:

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.8.1

    - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

    - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
