name: Build wheels
description: Builds wheels for release

runs:
  using: composite

  steps:

    - name: Install cibuildwheel
      shell: bash
      run: python -m pip install cibuildwheel==2.8.1

    - name: Build wheels
      shell: bash
      #run: python3 setup.py bdist_wheel
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp38* # pp* #cp${{ matrix.python }}-abi3-${{ matrix.platform_id }}
        CIBW_SKIP: pp* *-musllinux*
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_PRERELEASE_PYTHONS: 1
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""


