name: Release # workflow name
on: # trigger
  release:
    branches: [master]
    types:
      - created
  # push:
  #   branches: [dev]


# parallel jobs to perform
jobs:
  # === unittest execution ===
  build_wheel:
    runs-on: ubuntu-latest # runner

    steps:
      - name: Set Github Workspace # access Github Workspace
        uses: actions/checkout@v2
      - name: Set up Python 3.x # set architecture and Python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64" # architecture

      - name: Run unittests
        uses: ./.github/common/unit_tests

      - name: Build wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist