name: CD # workflow name
on: # trigger
  release:
    branches: [master]
    types:
      - created
  push:
    branches: [release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - name: Set Github Workspace
        uses: actions/checkout@v2
      - name: Set up Python 3.x # set architecture and Python3
        uses: actions/setup-python@v3

      - name: Install dependencies
        uses: ./.github/common/install_dependencies

      - name: Build wheels
        uses: ./.github/common/build_wheels
